Repository avoevodin/django_tutorial, pull requests merged in 2021-03, with the labels that each got.

#1 added restrictions on displaying questions without choices for index,…
  mysite/polls/tests.py
  mysite/polls/views.py
Labels: enhancement

#2 fixed README.md
  README.md
Labels: documentation

#6 Feature base template #3
  mysite/polls/templates/polls/base.html
  mysite/polls/templates/polls/detail.html
  mysite/polls/templates/polls/index.html
  mysite/polls/templates/polls/results.html
Labels: enhancement

#8 Feature translation #4
  .gitignore
  LOCALIZATION_TUTORIAL.md
  mysite/locale/en/LC_MESSAGES/django.po
  mysite/locale/ru/LC_MESSAGES/django.po
  mysite/mysite/settings.py
  mysite/polls/__init__.py
  mysite/polls/apps.py
  mysite/polls/models.py
  mysite/polls/templates/polls/base.html
  mysite/polls/templates/polls/detail.html
  mysite/polls/templates/polls/index.html
  mysite/polls/templates/polls/results.html
  mysite/polls/views.py
Labels: enhancement

#9 * added templates for admin #7
  mysite/locale/en/LC_MESSAGES/django.po
  mysite/locale/ru/LC_MESSAGES/django.po
  mysite/mysite/settings.py
  mysite/polls/admin.py
  mysite/polls/models.py
  mysite/templates/admin/base_site.html
  mysite/templates/polls/base.html
  mysite/templates/polls/detail.html
  mysite/templates/polls/index.html
  mysite/templates/polls/results.html
Labels: enhancement

#10 * updated dbms to postgres with docker
  .gitignore
  DOCKER_TUTORIAL.md
  README.md
  mysite/mysite/settings.py
  requirements.txt
Labels: documentation, enhancement

#11 updated settings.py and readme with env vars and static files.
  .gitignore
  DOCKER_TUTORIAL.md
  ENV_VARS_TUTORIAL.md
  README.md
  README_DEV.md
  mysite/mysite/settings.py
Labels: documentation, enhancement

#12 Feature static files
  .gitignore
  README.md
  WSGI_TUTORIAL.md
  mysite/uwsgi.ini
  requirements.txt
Labels: documentation, enhancement

#13 * Added tutorial for auto-deploy of the Docker container
  .dockerignore
  DOCKER_AUTO_DEPLOY_TUTORIAL.md
  DOCKER_TUTORIAL.md
  Dockerfile
  README.md
  WSGI_TUTORIAL.md
  mysite/uwsgi.ini
  requirements_docker.txt
Labels: documentation
